### ISSUE TITLE
版本v1.0.0,plugin v0.0.1,go version go1.16.4 linux/amd64

### ISSUE THREAD

**Issue by userInner** [hyperbench/hyperbench#54]
root@tmd-QiTianM610-N000:/gopath/src/test0# ./hyperbench start benchmark/hyperchain/local
[blockchain][ERROR] 18:44:14.027 blockchain.go:25 plugin failed: plugin.Open("./hyperchain"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf568f6]

goroutine 1 [running]:
plugin.lookup(...)
	plugin/plugin_dlopen.go:138
plugin.(*Plugin).Lookup(...)
	plugin/plugin.go:40
github.com/hyperbench/hyperbench/plugins/blockchain.NewBlockchain(0xc0004110f8, 0x5, 0xc000098540, 0x25, 0xc000098580, 0x23, 0x0, 0x0, 0x0, 0xc0004e9740, ...)
	github.com/hyperbench/hyperbench/plugins/blockchain/blockchain.go:33 +0xf6
github.com/hyperbench/hyperbench/vm/lua.(*VM).setPlugins(0xc00040c600, 0xc000400c00, 0x0, 0xc0003c2aa0)
	github.com/hyperbench/hyperbench/vm/lua/lua.go:265 +0x378
github.com/hyperbench/hyperbench/vm/lua.NewVM(0xc0004e9e60, 0xc00040c600, 0x0, 0x0)
	github.com/hyperbench/hyperbench/vm/lua/lua.go:56 +0x135
github.com/hyperbench/hyperbench/vm.NewVM(0xc000098462, 0x3, 0xc000098440, 0x25, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0003fbb00, 0x0, 0x7fa6802e8bd0, 0xc00040c5c0)
	github.com/hyperbench/hyperbench/vm/vm.go:68 +0xe5
github.com/hyperbench/hyperbench/core/controller/master.NewLocalMaster(0x0, 0x0, 0x0)
	github.com/hyperbench/hyperbench/core/controller/master/master.go:80 +0x148
github.com/hyperbench/hyperbench/core/controller.NewController(0x7ffc205706e9, 0x1a, 0x0, 0x0)
	github.com/hyperbench/hyperbench/core/controller/controller.go:48 +0x34
github.com/hyperbench/hyperbench/cmd.runBenchmark(0x7ffc205706e9, 0x1a)
	github.com/hyperbench/hyperbench/cmd/cobra.go:118 +0x52
github.com/hyperbench/hyperbench/cmd.addRun.func1(0x25d3c20, 0xc000119600, 0x1, 0x1)
	github.com/hyperbench/hyperbench/cmd/cobra.go:61 +0xcf
github.com/spf13/cobra.(*Command).execute(0x25d3c20, 0xc0001195d0, 0x1, 0x1, 0x0, 0x0)
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x33a
github.com/spf13/cobra.(*Command).ExecuteC(0x25d41e0, 0x0, 0x0, 0xc00005c740)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x395
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	github.com/hyperbench/hyperbench/main.go:16 +0xe5

**Comment by liuxiaomeiG** [comment]
#51 可参考这个问题的解决思路
